apiVersion: v2
appVersion: 2.11.0
description: multicluster-engine operator chart for non-OpenShift Kubernetes platforms
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine
sources:
- quay.io/stolostron/cmb-operator-bundle:2.11.0-BACKPLANE-2026-02-02-18-37-27
type: application
version: 2.11.0
